### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [RiProG-id/RiProG-AI#2]
The Readme says this Magisk module is "open source" – but I cannot find any clue what license is used. Could you please clarify? And are there any instructions on how to configure/use the module? Thanks in advance!

**Comment by RiProG-id** [comment]
This module is still in the development stage, I accept the suggestion, Thanks

**Comment by RiProG-id** [comment]
Closed issue

**Comment by IzzySoft** [comment]
Of course suggestions can be given – but with the issue closed and no license seen, I'm not sure if you're still following them? In the hope you will, @RiProG-id – let me make some:

* if you prefer a very liberal license: some public domain license like WTFPL or Unlicense
* if you prefer "just liberal": MIT, Apache-2.0, some BSD-style license
* should it be rather copy-left: pick a GPL or AGPL license

for guidance, please see the list at [SPDX](https://spdx.org/licenses/). Focus on licenses approved by OSI/FSF. The 7 I named explicitly are those most frequently picked.

**Comment by RiProG-id** [comment]
I don't understand licenses or anything like that, can you help me by contacting the @RiProG telegram

**Comment by IzzySoft** [comment]
Sorry, but I'm not using Telegram. However, I gladly help if I can.

In short, a license is on one hand protecting your code against plagiarism, giving "forkers" clear rules – while on the other hand giving them some "safety" against receiving copyright claims, due to the very same rules. Which license to choose thus depends on how much freedom you want to give, and how much protection you need. So basically you can go from "total freedom" (aka "do whatever you want with it", like "public domain" – matching licenses would be [Unlicense](https://spdx.org/licenses/Unlicense.html) or [WTFPL](https://spdx.org/licenses/WTFPL.html)), via lenient licenses like BSD-style, MIT, Apache-2 – up to strict copy-left ones like GPL or AGPL.
