### ISSUE TITLE
Notification toggle?

### ISSUE THREAD

**Issue by Mokura** [RiProG-id/RiProG-AI#3]
Would it be possible to add an option in the terminal menu to disable the mode-switching notifications for auto mode?  I keep thinking I'm getting a notification from something else when it's usually the module service switching from daily to sleep.

**Comment by Roterfux** [comment]
Excellent idea. 
Had to remove piprog, since the notifications are annoying. Sorry

**Comment by NeonLightning** [comment]
odd i'm still getting it i'm using 3.4 beta

**Comment by NeonLightning** [comment]
had to install gravitybox to make my notifications quiet without making my ringtone quiet because riprog keeps sending those notifications.

**Comment by Roterfux** [comment]
My answer was not clear, sorry. I had the same experience and therefore removed riprog

**Comment by NeonLightning** [comment]
looks like you can remove like 4 lines to remove the notifications but i'm not sure how to build an android program

**Comment by NeonLightning** [comment]
or scratch that. just toggle notification to false. edit riprog file inside the release zip and install that

**Comment by RiProG-id** [comment]
Maybe in the next update I will try to add terminal features for a while you can edit feature.txt in the module folder

**Comment by NeonLightning** [comment]
> Maybe in the next update I will try to add terminal features for a while you can edit feature.txt in the module folder

I was wondering if it seems more of a debug thing to have it on by default personally.
